/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'saumit' at '4/1/17 1:11 PM' with Gradle 3.1
 *
 * @author saumit, @date 4/1/17 1:11 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
